# -*- coding: utf-8 -*-
"""Copy of QR CODE GENERATION

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1U7mIw-69fsbuJk6DvGrtv1whBzLIXaMY
"""

!pip install qrcode

import qrcode
a=qrcode.make("https://swayam.gov.in/")
a.save("test.png")
a